"""add poster_url to movies

Revision ID: a3102af0073f
Revises: 0002
Create Date: 2026-09-18 11:11:38.758459
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a3102af0073f'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###