"""add poster_url to movies

Revision ID: dc54f0bd6c44
Revises: a3102af0073f
Create Date: 2026-09-18 11:38:06.852930
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc54f0bd6c44'
down_revision: Union[str, None] = 'a3102af0073f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###